.PHONY: all
all:
	make -C array88 $@
	make -C display $@
	make -C lcd_test $@
	make -C menu_test $@

.PHONY: clean
clean:
	make -C array88 $@
	make -C display $@
	make -C lcd_test $@
	make -C menu_test $@
