.PHONY: all
all:
	make -C array88 $@
	make -C display $@
	make -C lcd_test $@
	make -C menu_test $@
	make -C rtc_test $@
	make -C glcd_test $@
	make -C sdcard_test $@
	make -C term_test $@

.PHONY: clean
clean:
	make -C array88 $@
	make -C display $@
	make -C lcd_test $@
	make -C menu_test $@
	make -C rtc_test $@
	make -C glcd_test $@
	make -C sdcard_test $@
	make -C term_test $@
